config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :posts do
  resources :comments
end

root "posts#index"

get '/about', to: 'pages#about'
get '/topmovies', to: 'pages#topmovies'
get 'video' => 'pages#video'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user # => en base de donees user_id dans la table Comments
  validates_presence_of :body, :post_id, :user_id

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  validates :user_id, presence: true

  mount_uploader :image, ImageUploader

  belongs_to :user # => user_id dans Posts

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :avatar_cache])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body, :avatar))
    @comment.user_id = current_user.id
    @comment.save!

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :avatar)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def About
    render 'pages/about'
  end

  def topmovies
    render 'pages/topmovies'
  end

  def video
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body, :image))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path

  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def self_or_other(comment)
    comment.user == current_user ? "self" : "other"
  end

  def can_edit_comment?(comment)
    comment.user_id == current_user.id
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def can_edit_post?(post)
    post.user_id == current_user.id
  end
end

app/views/comments/_comment.html.erb
<div class="bubble">
  <div class="content">
    <p class= "avatarbubble"><%= image_tag comment.user.avatar.medium.url %></p>
    <p class="copy"><%= comment.body %></p>
  </div>
  <p class="time"><%= comment.created_at.strftime("%d %b  %Y at %I:%M%p") %>
  </p>

  <% if user_signed_in? && can_edit_comment?(comment)%>
    <p><%= link_to 'Delete', [comment.post, comment],
                    method: :delete,
                    class: "button_comments",
                    data: { confirm: 'Are you sure?'} %>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div id="logo">
    <%= link_to root_path do %>
    <%= image_tag "logo.svg"%>
    <% end %>
  </div>

  <ul>
    <li class="category">Website</li>
    <li><%= link_to"Top Movies",topmovies_path %></li>
    <li><%= link_to"Blog", root_path %></li>
    <li><%= link_to"About", about_path %></li>
  </ul>

  <ul>
    <li class="category">Social</li>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">Instagram</a></li>
    <li><a href="#">Facebook</a></li>
    <li><a href="#">Email</a></li>
  </ul>

  <% if !user_signed_in? %>
  <p class="sign_in">Admin Login</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application' 'http://fonts.googleapis.com/css?family=Raleway:400,700'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if controller_name != "pages" || action_name == 'about' || action_name == 'video' %>
    <%= render partial: 'layouts/sidebar' %>

    <div id="main_content">
      <div id="header">
        <%if current_page? (root_path) %>
        <p>All Posts</p>
        <% elsif current_page?(about_path) %>
        <p>About</p>
        <%else%>
        <%= link_to"Back to All Posts", root_path %>
        <% end %>


        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <% if !user_signed_in? %>
          <button class="button"><%= link_to "Sign In", new_user_session_path %></button>
          <button class="button"><%= link_to "Sign Up", new_user_registration_path %></button>
          <% else %>
          <button class="button"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></button>
          <%= link_to edit_user_registration_path do %>
          <%= image_tag current_user.avatar.medium.url, class: "avatar_nav" if current_user.avatar.url %>
          <% end %>
          <% end %>

        </div>

      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end %>
      <% end %>
      <%= yield %>

</div>

  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile">
		<%= image_tag "avatar.png", class:"imgabout" %>
	</div>

	<div id="content">
		<h1>Hey, I'm FLorian Lahitte</h1>
		<p>Welcome to my Movie Blog.</p>
		<p>This week I built a blog in Rails 5. You're actually on the demo application right now. Cool stuff, right!.</p>
		<p>If you'd like to follow me on <a href="https://github.com/captainflo" target="_blank">Github</a> or on <a href="https://www.linkedin.com/in/florianlahitte"target="_blank">Linkedin</a>
		, or if you want see my <a href="http://eepurl.com/02olT">Resume</a>.</p>
	</div>
</div>

app/views/pages/topmovies.html.erb
<div class="topmovies">
<div class="main">
  <div class="sidebar-hover">
    <% if !user_signed_in? %>
    <p class="pagination1"><%= link_to "Sign In", new_user_session_path %></p>
    <p class="pagination2"><%= link_to "Sign Up", new_user_registration_path %></p>
    <% else %>
    <%= link_to edit_user_registration_path do %>
    <%= image_tag current_user.avatar.medium.url, class: "avatar_nav" if current_user.avatar.url %>
    <% end %>
    <p class="pagination1"><%= link_to "New Post", new_post_path %></p>
    <p class="pagination2"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
    <% end %>

    <p class="pagination3"><%= link_to "Blog", root_path %></p>
    <p class="pagination4"><%= link_to "Video", video_path %></p>

    <p class="pagination">
      <span class="page">Movies</span> / <span class="total-pages">08</span>
    </p>
  </div>

  <div class="sidebar-real">
    <div data-page="1" class="nav-elem nav-1 active"></div>
    <div data-page="2" class="nav-elem nav-2"></div>
    <div data-page="3" class="nav-elem nav-3"></div>
    <div data-page="4" class="nav-elem nav-4"></div>
    <div data-page="5" class="nav-elem nav-5"></div>
    <div data-page="6" class="nav-elem nav-6"></div>
    <div data-page="7" class="nav-elem nav-7"></div>
    <div data-page="8" class="nav-elem nav-8"></div>
  </div>
  <div class="sections">
    <div class="section section-1">
      <div class="left-part">
        <%= image_tag "suicide-squad-movie-2016-poster.jpeg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading"><a href="/posts/3">Suicide Squad<a/></h2>
        <p class="additional-text">Fearing that the world is vulnerable to otherworldly threats,
        the Government enlists the disposable Task Force X on a high-risk mission in exchange for
         absolution: Meanwhile, the Joker operates his own agenda.</p>
      </div>
    </div>
    <div class="section section-2">
      <div class="left-part">
        <%= image_tag "mad-max-poster.jpg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading"><a href="/posts/1">Mad Maxmad Fury Road</a></h2>
        <p class="additional-text">
        A woman rebels against a tyrannical ruler in
        postapocalyptic Australia in search for her home-land with the help of a
        group of female prisoners, a psychotic worshipper, and a drifter named Max.</p>
      </div>
    </div>
    <div class="section section-3">
      <div class="left-part">
        <%= image_tag "img1.jpeg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading" href="/posts/2">Avatar</h2>
        <p class="additional-text">A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.</p>
      </div>
    </div>
    <div class="section section-4">
      <div class="left-part">
        <%= image_tag "star wars.jpg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading"><a href="/posts/2">Star Wars : Episode VII</a></h2>
        <p class="additional-text">Three decades after the defeat of the Galactic Empire, a new threat arises. The First Order attempts to rule the galaxy and only a ragtag group of heroes can stop them, along with the help of the Resistance.</p>
      </div>
    </div>
    <div class="section section-5">
      <div class="left-part">
        <%= image_tag "avanger.jpg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading">Avengers</h2>
        <p class="additional-text">Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.</p>
      </div>
    </div>
    <div class="section section-6">
      <div class="left-part">
        <%= image_tag "hobbit.jpg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading">The Hobbit</h2>
        <p class="additional-text">Bilbo and Company are forced to engage in a war against an array of combatants and keep the Lonely Mountain from falling into the hands of a rising darkness.</p>
      </div>
    </div>
    <div class="section section-7">
      <div class="left-part">
        <%= image_tag "backfutur.jpg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading">Back to the Future</h2>
        <p class="additional-text">Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.</p>
      </div>
    </div>
    <div class="section section-8">
      <div class="left-part">
        <%= image_tag "hr_Posters_1.jpg", class: "topmovies" %>
      </div>
      <div class="content">
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <div class="bg-part"></div>
        <h2 class="section-heading"><a href="http://codepen.io/suez/public/" target="_blank">The Dark Night</a></h2>
        <p class="check-out additional-text"> When the menace known as the Joker
        wreaks havoc and chaos on the people of Gotham, the caped crusader must
        come to terms with one of the greatest psychological tests of his ability
        to fight injustice.</p>
      </div>
    </div>
  </div>

</div>
</div>

app/views/pages/video.html.erb
<h1 class="videos">Top video</h1>

<div id="contenair_video">
<div class="element">Element 1
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
</div>
<div class="element">Element 2</div>
<div class="element">Element 3</div>
<div class="element">Element 4</div>
<div class="element">Element 5</div>
<div class="element">Element 6</div>
<div class="element">Element 7</div>
<div class="element">Element 8</div>
</div>



<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>
<iframe src="https://www.youtube.com/embed/eOrNdBpGMv8" frameborder="0" allowfullscreen></iframe>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1> Edit Post</h1>

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
  <div class="bubble_attachement">
    <div class="preview">
      <% if @posts.any? %>
       <%= image_tag post.image.url(:large) %>
   <% end %>
    </div>
    <div class="content">
      <h2 class="title"><%=link_to post.title, post %></h2>
      <p class="description"><%= post.body %></p>
      <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
    </div>
  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1> New Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>
  <br>
  <div class="principal">
    <div class="element">
      <%= image_tag @post.image.url(:large)%>
    </div>
    <div class="element1">
      <p class="body">
        <%= @post.body %>
      </p>
    </div>
  </div>

  <p class="date">
    submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? && can_edit_post?(@post) %>
      <%= link_to 'Edit', edit_post_path(@post) %>
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
      <% end %>
  </p>

  <div id='comments'>
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>